use std::process::Command;

use cargo_metadata::camino::Utf8PathBuf;
use color_eyre::eyre::{self, WrapErr as _, bail, ensure};

use crate::{
    report::{ReportContext, RunReport},
    sandbox::{SandboxAction, SandboxBootstrapConfig},
    scenario::{self, ScenarioParameters},
    util::{
        env::{
            FOTON_EXE_PATH_ENVVAR_NAME, FOTON_EXECUTION_ENVIRONMENT_ENVVAR_NAME,
            FOTON_FIXTURE_DIR_PATH_ENVVAR_NAME,
        },
        fs as fs_util, process as process_util, sys as sys_util,
    },
};

/// Internal arguments for the sandbox bootstrap command.
///
/// This command is launched inside Windows Sandbox by the sandbox runner and
/// is not intended for direct invocation.
#[derive(Debug, clap::Args)]
pub(in crate::command) struct BootstrapArgs {
    /// Internal marker indicating that this command was launched inside
    /// Windows Sandbox by the sandbox runner.
    #[clap(long)]
    launched_inside_sandbox: bool,
    /// Internal flag to rerun bootstrap actions in a child process with
    /// redirected stdout and stderr.
    #[clap(long)]
    run_as_child_process: bool,
    /// Path to the sandbox bootstrap config generated by the sandbox runner.
    #[clap(long)]
    config: Utf8PathBuf,
}

pub(in crate::command) fn dispatch(args: &BootstrapArgs) -> eyre::Result<()> {
    let BootstrapArgs {
        launched_inside_sandbox,
        run_as_child_process,
        config,
    } = args;

    ensure!(
        *launched_inside_sandbox,
        "bootstrap command must be launched inside Windows Sandbox through `cargo xtask sandbox` subcommands"
    );

    let config = fs_util::read_json("sandbox bootstrap config", config)?;
    if *run_as_child_process {
        dispatch_child(&config)
    } else {
        let res = dispatch_parent(args, &config);
        let _file = fs_util::create_file("complete stamp", &config.complete_stamp)?;
        res
    }
}

fn dispatch_parent(args: &BootstrapArgs, config: &SandboxBootstrapConfig) -> eyre::Result<()> {
    let user_envs = [
        (
            FOTON_EXECUTION_ENVIRONMENT_ENVVAR_NAME,
            config.execution_environment.as_str(),
        ),
        (FOTON_EXE_PATH_ENVVAR_NAME, config.foton_exe.as_str()),
        (
            FOTON_FIXTURE_DIR_PATH_ENVVAR_NAME,
            config.fixture_dir.as_str(),
        ),
    ];
    sys_util::set_user_envs(user_envs.iter().copied())
        .wrap_err("failed to set user environment variables")?;

    fs_util::create_dir_all("output directory", &config.output_dir)?;

    let mut cmd = Command::new(&config.xtask_exe);
    cmd.arg("bootstrap")
        .arg("--launched-inside-sandbox")
        .arg("--run-as-child-process")
        .arg("--config")
        .arg(&args.config)
        .envs(config.envs.iter().map(|(k, v)| (k, v)));
    let exec_result = process_util::exec_command("bootstrap", &config.output_dir, &mut cmd)?;

    if !exec_result.success {
        bail!(
            "bootstrap child process failed with status {}",
            exec_result.exit_status
        );
    }

    Ok(())
}

fn dispatch_child(config: &SandboxBootstrapConfig) -> eyre::Result<()> {
    let kind = config.action.to_kind();
    let (report_json, (res, report)) = match &config.action {
        SandboxAction::Noop => return Ok(()),
        SandboxAction::RunTests {
            test_exes,
            report_json,
        } => (
            report_json,
            RunReport::capture(config.run_id, kind, &config.output_dir, |cx| {
                run_test(cx, test_exes)
            }),
        ),
        SandboxAction::RunScenario {
            scenario,
            report_json,
        } => (
            report_json,
            RunReport::capture(config.run_id, kind, &config.output_dir, |cx| {
                let params = build_scenario_parameters(config);
                scenario::run(cx, *scenario, &params)
            }),
        ),
    };
    fs_util::write_json("run report", report_json, &report)?;
    res
}

fn run_test(cx: &ReportContext, test_exes: &[Utf8PathBuf]) -> eyre::Result<()> {
    for test_exe in test_exes {
        let mut cmd = Command::new(test_exe);
        let res = cx.exec_command(&mut cmd)?;
        if !res.success {
            bail!(
                "test executable `{test_exe}` failed with status {}",
                res.exit_status
            );
        }
    }
    Ok(())
}

fn build_scenario_parameters(config: &SandboxBootstrapConfig) -> ScenarioParameters {
    ScenarioParameters {
        foton_exe: config.foton_exe.clone(),
        fixture_dir: config.fixture_dir.clone(),
    }
}
