use std::process::Command;

use cargo_metadata::camino::{Utf8Path, Utf8PathBuf};
use color_eyre::eyre::{self, WrapErr as _, bail, ensure};
use serde::{Deserialize, Serialize};

use crate::{
    report::{ReportContext, RunId, RunKind, RunReport},
    scenario::{self, Scenario},
    util::{
        env::{
            FOTON_EXE_PATH_ENVVAR_NAME, FOTON_EXECUTION_ENVIRONMENT_ENVVAR_NAME,
            FOTON_FIXTURE_DIR_PATH_ENVVAR_NAME,
        },
        fs as fs_util, process as process_util, sys as sys_util,
    },
};

#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct SandboxBootstrapConfig {
    pub(crate) execution_environment: String,
    pub(crate) foton_exe: Utf8PathBuf,
    pub(crate) xtask_exe: Utf8PathBuf,
    pub(crate) fixture_dir: Utf8PathBuf,
    pub(crate) output_dir: Utf8PathBuf,
    pub(crate) complete_stamp: Utf8PathBuf,
    pub(crate) run_id: RunId,
    pub(crate) action: SandboxAction,
    pub(crate) envs: Vec<(String, String)>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum SandboxAction {
    Noop,
    RunTests {
        test_exes: Vec<Utf8PathBuf>,
        report_json: Utf8PathBuf,
    },
    RunScenario {
        scenario: Scenario,
        report_json: Utf8PathBuf,
    },
}

impl SandboxAction {
    pub(crate) fn to_kind(&self) -> RunKind {
        match self {
            Self::Noop => RunKind::Noop,
            Self::RunTests { .. } => RunKind::Test,
            Self::RunScenario { scenario, .. } => RunKind::Scenario(*scenario),
        }
    }
}

/// Internal arguments for the sandbox bootstrap command.
///
/// This command is launched inside Windows Sandbox by the sandbox runner and
/// is not intended for direct invocation.
#[derive(Debug, clap::Args)]
pub(crate) struct BootstrapArgs {
    /// Internal marker indicating that this command was launched inside
    /// Windows Sandbox by the sandbox runner.
    #[clap(long)]
    launched_inside_sandbox: bool,
    /// Internal flag to rerun bootstrap actions in a child process with
    /// redirected stdout and stderr.
    #[clap(long)]
    run_as_child_process: bool,
    /// Path to the sandbox bootstrap config generated by the sandbox runner.
    #[clap(long)]
    config: Utf8PathBuf,
}

pub(crate) fn dispatch(args: &BootstrapArgs) -> eyre::Result<()> {
    let BootstrapArgs {
        launched_inside_sandbox,
        run_as_child_process,
        config,
    } = args;

    ensure!(
        *launched_inside_sandbox,
        "bootstrap command must be launched inside Windows Sandbox through `cargo xtask sandbox` subcommands"
    );

    let config = fs_util::read_json("sandbox bootstrap config", config)?;
    if *run_as_child_process {
        dispatch_child(&config)
    } else {
        let res = dispatch_parent(args, &config);
        let _file = fs_util::create_file("complete stamp", &config.complete_stamp)?;
        res
    }
}

fn dispatch_parent(args: &BootstrapArgs, config: &SandboxBootstrapConfig) -> eyre::Result<()> {
    let user_envs = [
        (
            FOTON_EXECUTION_ENVIRONMENT_ENVVAR_NAME,
            config.execution_environment.as_str(),
        ),
        (FOTON_EXE_PATH_ENVVAR_NAME, config.foton_exe.as_str()),
        (
            FOTON_FIXTURE_DIR_PATH_ENVVAR_NAME,
            config.fixture_dir.as_str(),
        ),
    ];
    sys_util::set_user_envs(user_envs.iter().copied())
        .wrap_err("failed to set user environment variables")?;

    fs_util::create_dir_all("output directory", &config.output_dir)?;

    let stdout_path = config.output_dir.join("bootstrap.stdout.txt");
    let stderr_path = config.output_dir.join("bootstrap.stderr.txt");
    let status_path = config.output_dir.join("bootstrap.status.txt");

    let stdout_file = fs_util::create_file("bootstrap stdout", &stdout_path)?;
    let stderr_file = fs_util::create_file("bootstrap stderr", &stderr_path)?;

    let mut cmd = Command::new(&config.xtask_exe);
    let status = cmd
        .arg("bootstrap")
        .arg("--launched-inside-sandbox")
        .arg("--run-as-child-process")
        .arg("--config")
        .arg(&args.config)
        .envs(config.envs.iter().map(|(k, v)| (k, v)))
        .stdout(stdout_file)
        .stderr(stderr_file)
        .status()
        .wrap_err("failed to spawn or wait for bootstrap process")?;

    fs_util::write("bootstrap status", &status_path, status.to_string())?;

    if !status.success() {
        bail!("bootstrap child process failed with status {status}");
    }

    Ok(())
}

fn dispatch_child(config: &SandboxBootstrapConfig) -> eyre::Result<()> {
    let kind = config.action.to_kind();
    let (report_json, (res, report)) = match &config.action {
        SandboxAction::Noop => return Ok(()),
        SandboxAction::RunTests {
            test_exes,
            report_json,
        } => (
            report_json,
            RunReport::capture(config.run_id, kind, |cx| {
                run_test(cx, test_exes, &config.output_dir)
            }),
        ),
        SandboxAction::RunScenario {
            scenario,
            report_json,
        } => (
            report_json,
            RunReport::capture(config.run_id, kind, |cx| {
                scenario::run_in_sandbox(cx, config, *scenario)
            }),
        ),
    };
    fs_util::write_json("run report", report_json, &report)?;
    res
}

fn run_test(
    cx: &ReportContext,
    test_exes: &[Utf8PathBuf],
    output_dir: &Utf8Path,
) -> eyre::Result<()> {
    for test_exe in test_exes {
        let mut cmd = Command::new(test_exe);
        let name = test_exe.file_stem().unwrap_or("test");
        let res = process_util::exec_command(cx, name, output_dir, &mut cmd)?;
        if !res.success {
            bail!(
                "test executable `{test_exe}` failed with status {}",
                res.exit_status
            );
        }
    }
    Ok(())
}
